name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install / test / build
        run: |
          cd app
          npm install
          npm run build
      - name: deploy app
        env:
          NETLIFY_AUTH_TOKEN: "nfp_K8vt2AodcbK16g7WhEuf5TaTsxZs7yec91ce"
          NETLIFY_SITE_ID: "f7ecc224-dcbe-41de-a84e-e6a33dfaba41"
        run: |
          npm install netlify-cli -g
          cd app
          touch netlify.toml
          echo '[build.environment]' > netlify.toml
          echo '  VITE_API_URL = "https://dancetapp-final-project.onrender.com"' >> netlify.toml
          netlify build
          netlify deploy --dir=./dist --prod
          rm netlify.toml
